export default {
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_NOT_AUTHORIZED: 'USER_NOT_AUTHORIZED',

  JWT_SECRET_IS_NOT_DEFINED: 'JWT_SECRET_IS_NOT_DEFINED',
} as const;
